main/urls.py
from main.views import base,auth_login,auth_logout,custom_404,auth_register
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base, name="inicio"),
    path('login', auth_login, name="login"),
    path('register', auth_register, name="register"),
    path('logout', auth_logout, name="logout"),
    path('', include('products.urls'))   ,
    path('', include('shopping_cart.urls')), 
    path('', include('categories.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = custom_404

shopping_cart/urls.py
from shopping_cart.views import base,add,delete,deleteAll
from django.urls import path

app_name ="shopping_cart"

urlpatterns = [
    path('cart/', base, name="lista"),
    path('cart/<int:productId>', add, name='add'),
    path('cart/delete/<int:cartId>', delete, name='delete'),
    path('cart/delete_all', deleteAll, name='delete_all'),
]

shopping_cart/models.py
from django.db import models
from django.conf import settings
from products.models import Product

class ShoppingCart(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.PROTECT, 
    )
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='shopping_carts'
    )
    createdAt = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        unique_together = ('user', 'product',)
        verbose_name = "Carrito de Compras"
        verbose_name_plural = "Carritos de Compras"

shopping_cart/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import HttpRequest, JsonResponse
from shopping_cart.models import ShoppingCart
from products.models import Product
from django.db import IntegrityError
from django.contrib import messages


@login_required(login_url="/login")
def base(req:HttpRequest):
    data = ShoppingCart.objects.select_related().filter(user= req.user)
    return render(req,"shopping_cart/base.html",{"carts":data})


@login_required(login_url="/login")
def add(req:HttpRequest,productId):
    if req.method != "POST":
        return JsonResponse({'status': 'error', 'message': 'Método no permitido'}, status=405)
    
    try:
        productMatch = Product.objects.get(id=productId)
        
        ShoppingCart.objects.create(
            user =  req.user,
            product =  productMatch
        )
        return JsonResponse({'status': 'ok', 'message': 'Producto añadido'}, status=202)
    except Product.DoesNotExist:
        return JsonResponse({'status': 'error', 'message': 'El producto Seleccionado no existe'}, status=404)
    except IntegrityError:
        return JsonResponse({'status': 'error', 'message': 'El producto seleccionado ya esta en el carrito'}, status=409)


def delete(req:HttpRequest,cartId):
    print(req.method)
    if req.method != "GET":
       messages.error(req, "Metodo no permitido")
       return redirect("/cart")
    try:
        productMatch = ShoppingCart.objects.get(id=cartId)
        productMatch.delete()
        messages.success(req, "Producto quitado del carrito")
        
        return redirect("/cart")
    
    except cartId.DoesNotExist:
        messages.error(req, "Este producto no existe")
        return redirect("/cart")

def deleteAll(req:HttpRequest):
    if req.method != "DELETE":
        return JsonResponse({'status': 'error', 'message': 'Método no permitido'}, status=405)
    try:
        ShoppingCart.objects.filter(user= req.user).delete()
        return JsonResponse({'status': 'error', 'message': 'Carrito comprado'}, status=202)
    except:
        return JsonResponse({'status': 'error', 'message': 'Error al comparar'}, status=404)

shopping_cart/templates/shopping_cart/base.html
{% extends "main/layout.html" %} {% block content %}

<section class="max-w-6xl w-full mx-auto px-3 py-2 pt-12">
  <div class="flex items-center justify-between mb-8 flex-wrap gap-4">
    <div>
      <h1 class="text-4xl md:text-5xl font-bold text-gray-900 mb-2">
        <i class="bi bi-basket2-fill"></i> Mi Carrito
      </h1>
      <p class="text-gray-600 font-semibold">
        Gestiona tus productos y completa tu compra
      </p>
    </div>
    <a
      id="buy-btn"
      href="{% url 'shopping_cart:lista' %}"
      class="bg-sky-400 btn md:w-fit w-full"
    >
      Comprar <i class="bi bi-basket2-fill"></i>
    </a>
  </div>

  <div class="space-y-4" id="cart_container">
    {% if carts %} {% for cart in carts %}
    <div
      id="cart-id-{{cart.id}}"
      class="cart-item-enter bg-[#F5E6CF] px-4 py-2 border-4 border-black"
    >
      <div class="flex gap-6 flex-wrap">
        <div class="flex-shrink-0">
          <img
            src=" {{cart.product.img.url}}"
            alt=" {{cart.product.name}}"
            class="w-24 h-24 object-cover rounded-lg bg-gray-100"
          />
        </div>

        <div class="flex-grow">
          <h3 class="text-lg font-bold text-gray-900 mb-2">
            {{cart.product.name}}
          </h3>

          <p class="text-orange-600 font-semibold">
            Precio:
            <span class="text-gray-900" id="cart-price-{{cart.id}}">
              {{cart.product.price}}</span
            >
          </p>
          <p class="text-orange-600 font-semibold mb-1">
            Unidades disponibles:
            <span class="text-gray-900" id="cart-price-{{cart.id}}">
              {{cart.product.stock}}</span
            >
          </p>

          <div class="flex items-center gap-3 mb-4">
            <button
              cart-id="{{cart.id}}"
              type-action="sub"
              class="btn bg-[#FE8B5A] btn-change-stock"
            >
              <i class="bi bi-dash" style="-webkit-text-stroke: 1px"></i>
            </button>
            <span
              id="ammount-cart-{{cart.id}}"
              max-ammount-value="{{cart.product.stock}}"
              class="px-4 py-2 border-black border-[3px] font-semibold text-xl text-center w-16 bg-slate-200"
              >1</span
            >
            <button
              cart-id="{{cart.id}}"
              type-action="add"
              class="bg-red-400 btn btn-change-stock"
            >
              <i class="bi bi-plus" style="-webkit-text-stroke: 1px"></i>
            </button>
          </div>
        </div>

        <div
          class="flex md:gap-0 gap-4 md:flex-col items-end justify-between md:w-fit w-full"
        >
          <form action="{% url 'shopping_cart:delete' cart.id %}">
            <button
              onclick="return confirm('¿Seguro seguro que quieres eliminar este preciado articulo')"
              class="bg-orange-600 btn w-full"
            >
              <i class="bi bi-trash3-fill"></i>
            </button>
          </form>

          <div>
            <p class="font-semibold text-gray-600 mb-1">Total:</p>
            <p
              id="total-ammount-{{cart.id}}"
              class="total-ammount text-2xl font-bold text-black"
            >
              ${{cart.product.price}}
            </p>
          </div>
        </div>
      </div>
    </div>
    {% endfor %} {% else %}
    <div
      data-aos="flip-up"
      class="bg-[#F5E6CF] shadow-lg p-8 text-center flex-1 border-4 border-black"
    >
      <div class="mb-6 flex justify-center">
        <div
          class="w-20 h-20 bg-amber-500 rounded-full flex items-center justify-center border-4 border-black"
        >
          <i class="bi bi-basket2-fill text-3xl"></i>
        </div>
      </div>

      <h2 class="text-2xl font-bold mb-2">Carrito Vacio</h2>
      <p class="text-gray-600 font-semibold mb-6 leading-relaxed">
        No encontramos productos para mostrar en el carrito, intenta añadir uno.
      </p>
    </div>
    {% endif %}
  </div>
</section>

<script>
  document.addEventListener("DOMContentLoaded", () => {
    const stockButtons = document.querySelectorAll(".btn-change-stock");
    [...stockButtons].forEach((btn) => {
      btn.addEventListener("click", (e) => {
        const typeAction = btn.getAttribute("type-action");
        const id = btn.getAttribute("cart-id");
        const ammount = document.getElementById(`ammount-cart-${id}`);
        if (typeAction == "add") {
          const maxValue = Number(ammount.getAttribute("max-ammount-value"));
          if (Number(ammount.textContent.trim()) + 1 > maxValue) return;
          ammount.innerHTML = (
            Number(ammount.textContent.trim()) + 1
          ).toString();
        } else {
          if (Number(ammount.textContent.trim()) - 1 < 1) return;
          ammount.innerHTML = (
            Number(ammount.textContent.trim()) - 1
          ).toString();
        }
        const price = document.getElementById(`cart-price-${id}`).textContent;
        calculateTotal(Number(ammount.textContent), Number(price), id);
      });
    });

    const calculateTotal = (ammount, price, id) => {
      document.getElementById(`total-ammount-${id}`).textContent = `$ ${
        ammount * price
      }`;
    };
  });
</script>
{% endblock %}