categories/urls.py
from categories.views import  base,add,update,delete
from django.urls import path

app_name = "categories"

urlpatterns = [
    path('categories', base, name="lista"),
    path('categories/add', add, name="add"),
     path('categories/update/<int:catId>',update , name="update"),
    path('categories/delete/<int:catId>', delete, name="delete"),
]

main/urls.py
from main.views import base,auth_login,auth_logout,custom_404,auth_register
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base, name="inicio"),
    path('login', auth_login, name="login"),
    path('register', auth_register, name="register"),
    path('logout', auth_logout, name="logout"),
    path('', include('products.urls'))   ,
    path('', include('shopping_cart.urls')), 
    path('', include('categories.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = custom_404

categories/models.py
from django.db import models

class Categorie(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField()
    createdAt = models.DateTimeField(auto_now_add=True)

categories/forms.py
from django import forms
from .models import Categorie

class CrearCategorie(forms.ModelForm):
    class Meta:
        model = Categorie
        fields = ['name',"description"]

categories/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from categories.models import Categorie
from django.contrib import messages
from django.http import HttpRequest
from django.contrib.auth import logout
from django.contrib.messages import get_messages
from django.db.models import ProtectedError
from .forms import CrearCategorie

@login_required(login_url="login")
def base(req:HttpRequest):
    if(not req.user.is_superuser):
        current_messages = get_messages(req)
        for _ in current_messages:
            pass
        logout(req)
        messages.error(req,"Usuario no autorizado")
        return redirect("/login")
    
    categories = []
    
    termino_busqueda = req.GET.get('q')
    if termino_busqueda:
        categories = Categorie.objects.filter(name__icontains=termino_busqueda)
    else:
        categories = Categorie.objects.all()
    return render(req,"categories/lista.html",{"categories":categories})


@login_required(login_url="login")
def add(req):
    if(not req.user.is_superuser):
        current_messages = get_messages(req)
        for _ in current_messages:
            pass
        logout(req)
        messages.error(req,"Usuario no autorizado")
        return redirect("/login")
    
    if req.method == "POST":
        newCategorie = CrearCategorie(req.POST,req.FILES)
        if newCategorie.is_valid():
            messages.success(req,"Categoria Creada")
            newCategorie.save()
            return redirect("/categories")
    return render(req,"categories/create.html")


@login_required(login_url="login")
def delete(req,catId):
    try:
        if(not req.user.is_superuser):
            current_messages = get_messages(req)
            for _ in current_messages:
                pass
            logout(req)
            messages.error(req,"Usuario no autorizado")
            return redirect("/login")
        categorie = get_object_or_404(Categorie,id = catId)
        categorie.delete()
        messages.success(req, "Categoria eliminada ")
        return redirect("/categories")
    except ProtectedError:   
        messages.error(req, "Esta categoria esta siendo usado, no se puede eliminar ")
        return redirect("/categories") 
    

@login_required(login_url="login")
def update(req, catId):
    if(not req.user.is_superuser):
        current_messages = get_messages(req)
        for _ in current_messages:
            pass
        logout(req)
        messages.error(req,"Usuario no autorizado")
        return redirect("/login")
    categorie = get_object_or_404(Categorie, id=catId)
    if req.method == "POST":
        form = CrearCategorie(req.POST, req.FILES, instance=categorie)
        if form.is_valid():
            form.save()
            messages.success(req, "Categoria actualizada")
            return redirect("/categories")
        else:
            messages.error(req, "Datos inválidos, revisa el formulario.")
    return render(req, "categories/create.html", {"categorie": categorie})

categories/templates/categories/create.html
{% extends "main/layout.html" %} {% load static %} {% block content %}
<div class="max-w-2xl w-full mx-auto my-12">
  <div class="mb-8 px-3">
    <h1 class="text-4xl font-bold text-black mb-2">Formulario de Categoria</h1>
    <p class="text-gray-600">
      Completa los campos para crear o actualizar una categoria
    </p>
  </div>

  <div class="border-4 border-black shadow-lg p-8 mx-4">
    <form
      novalidate
      id="categorie_form"
      class="space-y-6"
      action="{% if categorie %}{% url 'categories:update' categorie.id %}{% else %}{% url 'categories:add' %}{% endif %}"
      method="post"
      enctype="multipart/form-data"
    >
      {% csrf_token %}
      <div>
        <label for="name" class="block font-semibold text-black">
          Nombre Categoria
        </label>
        <input
          type="text"
          id="name"
          name="name"
          placeholder="Ej: Tecnologia"
          class="w-full px-4 py-3 border-[3px] border-black focus:outline-none bg-[#F5E6CF] focus:border-amber-500 font-semibold transition-colors duration-300"
          value="{{categorie.name}}"
        />
        <span id="error_name" class="text-red-500 font-semibold"></span>
      </div>
      <div>
        <label for="description" class="block font-semibold text-black">
          Descripción
        </label>
        <textarea
          id="description"
          name="description"
          placeholder="Describe las características y el porque de la categoria"
          rows="5"
          class="w-full px-4 py-3 border-[3px] border-black focus:outline-none bg-[#F5E6CF] focus:border-amber-500 font-semibold transition-colors duration-300"
        >
{% if categorie %}{{ categorie.description }}{% endif %}</textarea
        >
        <span id="error_description" class="text-red-500 font-semibold"></span>
      </div>

      <div
        class="flex gap-4 pt-6 flex-wrap items-center md:justify-center w-full"
      >
        <button type="submit" class="btn w-full md:w-fit bg-emerald-500">
          {% if categorie %} Actualizar {% else %} Crear {% endif %}
        </button>
        <button type="reset" class="btn w-full md:w-fit bg-slate-200">
          {% if categorie %} Restaurar {% else %} Limpiar Formulario {% endif %}
        </button>
        <a
          href="{% url 'categories:lista' %}"
          class="btn text-center w-full md:w-fit bg-orange-500"
        >
          Cancelar
        </a>
      </div>
    </form>
  </div>
</div>

<script src="{% static 'main/js/create_categorie.js' %}"></script>

{% endblock %}

categories/templates/categories/lista.html
{% extends "main/layout.html" %}{% block content %}

<section class="max-w-6xl w-full mx-auto px-3 pt-12 pb-20">
  <div class="mb-8">
    <h1 class="text-4xl font-bold text-gray-900 mb-2">Gestión de Categories</h1>
    <p class="text-gray-600 font-semibold">
      Administra tus categorias de productos
    </p>
  </div>

  <div
    class="flex flex-col sm:flex-row gap-4 items-center justify-between my-12"
  >
    <div class="w-full sm:w-96">
      <form action="{% url 'categories:lista' %}" method="get">
        <div class="flex gap-2 items-end justify-center">
          <input
            type="text"
            name="q"
            placeholder="Buscar por nombre o descripción..."
            class="w-full px-4 bg-[#F5E6CF] py-2 border-[3px] font-semibold border-black focus:outline-none focus:border-sky-700 transition-all duration-300"
          />
          <button type="submit" class="btn bg-sky-400">
            <i style="-webkit-text-stroke: 1px" class="bi bi-search"></i>
          </button>
        </div>
      </form>
    </div>
    <a href="{% url 'categories:add' %}" class="btn bg-emerald-500">
      <i class="bi bi-plus-circle" style="-webkit-text-stroke: 1px"></i> Crear
      Categoria
    </a>
  </div>

  {% if categories %}

  <div class="space-y-3">
    {% for categorie in categories %}
    <div
      data-aos="flip-left"
      class="border-4 border-black bg-[#F5E6CF] p-4 rounded flex justify-between items-center flex-wrap"
    >
      <div>
        <h4 class="font-bold text-lg text-gray-900">{{categorie.name}}</h4>
        <p class="text-black font-semibold">{{categorie.description}}</p>
        <div class="flex gap-3">
          <p class="text-orange-600 font-semibold mb-1">
            Fecha Creacion:
            <span class="text-gray-900"> {{categorie.createdAt}}</span>
          </p>
        </div>
      </div>
      <div class="flex gap-2">
        <a
          href="{% url 'categories:update' categorie.id %}"
          class="bg-[#FF8C42] btn"
          >Editar</a
        >
        <form
          action="{% url 'categories:delete' categorie.id %}"
          method="DELETE"
        >
          <button
            onclick="return confirm('¿Seguro seguro que quieres eliminar este preciado articulo')"
            class="bg-red-400 btn produt-to-delete"
          >
            Eliminar
          </button>
        </form>
      </div>
    </div>

    {% endfor %}
  </div>
  {% else %}
  <div
    data-aos="flip-up"
    class="bg-[#F5E6CF] shadow-lg p-8 text-center flex-1 border-4 border-black"
  >
    <div class="mb-6 flex justify-center">
      <div
        class="w-20 h-20 bg-amber-500 rounded-full flex items-center justify-center border-4 border-black"
      >
        <i class="bi bi-tags-fill text-3xl"></i>
      </div>
    </div>

    <h2 class="text-2xl font-bold mb-2">Sin Categorias</h2>
    <p class="text-gray-600 font-semibold mb-6 leading-relaxed">
      No encontramos ninguna para mostrar. Intenta a recargar la pagina o crear
      alguna.
    </p>
    <a href="{% url 'categories:add' %}" class="btn bg-emerald-500">
      <i class="bi bi-plus-circle" style="-webkit-text-stroke: 1px"></i> Crear
      Categoria
    </a>
  </div>
  {% endif %}
</section>
{% endblock %}