categories/urls.py
from categories.views import  base,add,update,delete
from django.urls import path

app_name = "categories"

urlpatterns = [
    path('categories', base, name="lista"),
    path('categories/add', add, name="add"),
     path('categories/update/<int:catId>',update , name="update"),
    path('categories/delete/<int:catId>', delete, name="delete"),
]

main/urls.py
from main.views import base,auth_login,auth_logout,custom_404,auth_register
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', base, name="inicio"),
    path('login', auth_login, name="login"),
    path('register', auth_register, name="register"),
    path('logout', auth_logout, name="logout"),
    path('', include('products.urls'))   ,
    path('', include('shopping_cart.urls')), 
    path('', include('categories.urls')), 
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
handler404 = custom_404

products/urls.py
from products.views import  base,add,delete,update
from django.urls import path

app_name = "products"

urlpatterns = [
    path('products', base, name="lista"),
    path('products/add', add, name="add"),
    path('products/update/<int:productId>',update , name="update"),
    path('products/delete/<int:productId>', delete, name="delete"),
]

shopping_cart/urls.py
from shopping_cart.views import base,add,delete,deleteAll
from django.urls import path

app_name ="shopping_cart"

urlpatterns = [
    path('cart/', base, name="lista"),
    path('cart/<int:productId>', add, name='add'),
    path('cart/delete/<int:cartId>', delete, name='delete'),
    path('cart/delete_all', deleteAll, name='delete_all'),
]

main/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import  AuthenticationForm,UserCreationForm
from django.contrib.auth import login,logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from products.models import Product
from django.http import HttpRequest
import random
def base(req):
    products =  Product.objects.all()
    opciones_aos = [
        'fade-up', 
        'fade-down', 
        'zoom-in', 
        'flip-left'
    ]
    for i, product in enumerate(products):
        product.aos_animacion = random.choice(opciones_aos)
        product.aos_retraso = 0
    return render(req,"main/inicio.html",{"products":products})



def auth_login(req:HttpRequest):
    if req.user.is_authenticated:
        if req.user.is_superuser :
            return redirect("/products")
        else:
            return redirect("/")
        
    if req.method == "POST":
        form =  AuthenticationForm(data=req.POST)
        if form.is_valid():
            user = form.get_user()
            login(req,user)
            messages.success(req,"Inicio de sesion correcto")
            if user.is_superuser:
                return redirect("/products")
            else:
                return redirect("/")
        else:
            messages.success(req,"Credenciales incorrectas")
    return render(req,"main/login.html")


def auth_register(req:HttpRequest):
    if req.method == "POST":
        form = UserCreationForm(req.POST)
        if form.is_valid():   
            user =  form.save()
            login(req,user)
            messages.success(req,"Usuario registrado exitosamente")     
            return redirect("/")
        else:
            print(form.errors) 
            messages.success(req,"Datos ingresados invalidos")
    return render(req,"main/register.html")

@login_required(login_url="/login")
def auth_logout(req):
    logout(req)
    messages.success(req, "Sesion cerrada")
    return redirect("/login")

def custom_404(req,_):
    return render(req,"main/404.html", status=404)

main/templates/main/inicio.html
{% extends "main/layout.html" %} {% block content %} {% load static %}
<section
  class="min-h-screen flex items-center justify-center text-black font-bold"
>
  <div class="mx-auto px-4 text-center" data-aos="zoom-out-down">
    <h1 class="text-5xl md:text-6xl font-bold mb-6 leading-tight">
      Dinámico, enfocado en perifericos y electrónica
    </h1>
    <p class="text-xl md:text-2xl mb-8 text-gray-600 font-semibold mx-auto">
      Conectamos la última tecnología con tu día a día, ofreciéndote
      dispositivos que transforman cómo trabajas, juegas y vives. Descubre
      productos cuidadosamente seleccionados que combinan diseño excepcional,
      rendimiento superior y la calidad que mereces.
    </p>
  </div>
</section>
<hr />
<section
  class="min-h-screen flex items-start justify-center pt-6 pb-22 md:flex-row flex-col"
>
  <div data-aos="fade-up" class="sticky top-[30%] z-30">
    <h2
      class="text-4xl md:text-5xl font-bold text-center mb-4 p-6 text-gray-800"
    >
      Nuestros Productos
    </h2>
    <p class="text-center text-gray-600 mb-12 text-lg max-w-2xl mx-auto">
      Encuentra lo que necesitas, cuando lo necesitas
    </p>
  </div>
  <div class="max-w-6xl mx-auto px-4 w-full">
    <form id="form_with_token">{% csrf_token %}</form>
    <div class="gap-2 flex flex-wrap justify-center">
      {% if products %} {% for product in products %}
      <div
        data-aos="{{ product.aos_animacion }}"
        data-aos-delay="{{ product.aos_retraso }}"
        class="bg-[#F5E6CF] border-2 border-black max-w-[240px] w-full"
      >
        <img
          src="{{product.img.url}}"
          alt="Desarrollo Web"
          class="w-full h-32 object-cover"
        />
        <div class="w-full flex gap-1 p-1 pb-2 flex-col">
          <h3 class="font-bold text-black">{{product.name}}</h3>
          <p class="font-bold text-orange-600">${{product.price}}</p>
          <p
            class="text-gray-600 leading-relaxed truncate text-ellipsis max-w-[200ch]"
          >
            {{product.description}}
          </p>
          <button
            type="button"
            data-url-base="{% url 'shopping_cart:add' product.id %}"
            class="btn-add-cart btn bg-orange-500 mx-auto"
          >
            Agregar al carrito
          </button>
        </div>
      </div>
      {% endfor %} {% else %}
      <div
        data-aos="flip-up"
        class="bg-white rounded-lg shadow-lg p-8 text-center flex-1"
      >
        <div class="mb-6 flex justify-center">
          <div
            class="w-20 h-20 bg-gradient-to-br from-purple-200 to-purple-100 rounded-full flex items-center justify-center"
          >
            <svg
              class="w-10 h-10 text-purple-600"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                stroke-width="2"
                d="M20 13V6a2 2 0 00-2-2H6a2 2 0 00-2 2v7m16 0v5a2 2 0 01-2 2H6a2 2 0 01-2-2v-5m16 0h-2.586a1 1 0 00-.707.293l-2.414 2.414a1 1 0 01-.707.293h-3.172a1 1 0 01-.707-.293l-2.414-2.414A1 1 0 006.586 13H4"
              ></path>
            </svg>
          </div>
        </div>

        <h2 class="text-2xl font-bold text-purple-900 mb-2">Sin productos</h2>
        <p class="text-gray-600 mb-6 leading-relaxed">
          No encontramos productos para mostrar. Intenta a recargar la pagina o
          crear alguno.
        </p>
      </div>
      {% endif %}
    </div>
  </div>

  <script>
    const addToCart = async (url) => {
      try {
        const csrftoken = document
          .querySelector('meta[name="csrf-token"]')
          .getAttribute("content");

        const resp = await fetch(window.location.href + url.replace("/", ""), {
          method: "POST",
          headers: {
            "Content-Type": "application/json",
            "X-CSRFToken": csrftoken,
          },
        });

        let statusClass = "#16B981";
        const data = await resp.json();
        if (data.status != "ok") statusClass = "#FF6467";

        Toastify({
          text: data.message,
          duration: 3000,
          className: "btn",
          position: "right",
          style: {
            color: "black",
            background: statusClass,
          },
        }).showToast();
      } catch (e) {
        Toastify({
          text: data.message,
          duration: 3000,
          className: "btn",
          position: "right",
          style: {
            color: "black",
            background: "#FF6467",
          },
        }).showToast();
      }
    };
  </script>

  <script>
    document.addEventListener("DOMContentLoaded", () => {
      const buttons = document.querySelectorAll(".btn-add-cart");
      [...buttons].forEach((btn) => {
        btn.addEventListener("click", (e) => {
          const url = btn.getAttribute("data-url-base");
          addToCart(url);
        });
      });
    });
  </script>
</section>

{% endblock %}

main/templates/main/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="es" class="scroll-smooth">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta name="csrf-token" content="{{ csrf_token }}" />

    <title>TechFlow</title>

    <link rel="icon" type="image/x-icon" href="{% static 'main/icon.png' %}" />
    <!-- ICONS -->
    <link
      rel="stylesheet"
      href="{% static 'main/icons/bootstrap-icons.css' %}"
    />
    <!-- TAILWIND -->
    <link rel="stylesheet" href="{% static 'main/css/output.css' %}" />
    <!-- AOS - AUTOANIMATE -->
    <link rel="stylesheet" href="{% static 'main/aos/aos.css' %}" />
    <script src="{% static 'main/aos/aos.js' %}"></script>

    <!-- TOASTIFY -->
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'main/toastify/toastify.min.css' %}"
    />
    <script src="{% static 'main/toastify/toastify-js.js' %}"></script>
  </head>
  <body>
    {% if request.user and request.user.is_superuser %}
    <aside
      class="flex items-center md:flex-col gap-5 justify-center md:justify-start py-6 fixed w-full md:max-w-[100px] left-0 bottom-0 h-[60px] md:top-0 md:h-screen bg-[#F5E6CF] border-t-4 md:border-t-0 md:border-r-4 border-black z-50"
    >
      <h2 class="font-bold md:block hidden text-lg border-b-2 border-black">
        {{request.user.username}} <br />
        Admin
      </h2>
      <div class="text-center group">
        <a href="{% url 'inicio' %}" class="">
          <i class="bi bi-house-door-fill"></i>
          <span
            class="block font-semibold text-sm group-hover:underline decoration-2"
            >Inicio</span
          >
        </a>
      </div>

      <div class="text-center">
        <a href="{% url 'products:lista' %}" class="group">
          <i class="bi bi-box2-heart-fill font-bold"></i>
          <span
            class="block font-semibold text-sm group-hover:underline decoration-2"
            >Inventario</span
          >
        </a>
      </div>
      <div class="text-center">
        <a href="{% url 'categories:lista' %}" class="group">
          <i class="bi bi-tags-fill"></i>
          <span
            class="block font-semibold text-sm group-hover:underline decoration-2"
            >Categorias</span
          >
        </a>
      </div>
    </aside>

    {% endif %}

    <header
      class="bg-[#F5E6CF] sticky top-0 z-40 border-b-4 border-black {% if request.user and request.user.is_superuser %} md:ml-[100px] {% else %} {% endif %}"
    >
      <nav
        class="px-4 sm:px-6 lg:px-8 flex justify-center md:justify-between items-center py-3 gap-4 flex-wrap"
      >
        <div class="flex items-center gap-2">
          <a href="{% url 'inicio' %}" class="bg-amber-500 btn">
            <span class="font-bold">TechFlow</span>
            <i class="bi bi-house-door-fill"></i>
          </a>
        </div>

        {% if request.user.is_authenticated %}
        <div class="gap-2 flex items-center">
          <h3 class="font-bold text-xl text-black border-black border-r-4 pr-3">
            {{request.user.username}}
          </h3>
          <a href="{% url 'shopping_cart:lista' %}" class="bg-sky-400 btn">
            <i class="bi bi-basket2-fill"></i>
          </a>
          <a href="{% url 'logout' %}" class="btn bg-[#FB5557]">
            <i class="bi bi-door-closed-fill"></i>
          </a>
        </div>
        {% else %}
        <div class="mx-w-[400px] gap-2 flex">
          <a href="{% url 'login' %}" class="btn bg-sky-400">
            Iniciar Sesión
          </a>
          <a href="{% url 'register' %}" class="btn bg-orange-500">
            Registro
          </a>
        </div>
        {% endif %}
      </nav>
    </header>

    <!-- !NO MOVER ESTO DE AQUI -->
    <script>
      AOS.init();
    </script>

    <main
      class="{% if request.user and request.user.is_superuser %} md:ml-[130px] mb-[100px] md:mb-0 {% else %} {% endif %}"
    >
      {% block content %} {% endblock %}
    </main>

    {% if messages %} {% for message in messages %}
    <script>
      let statusClass = "#16B981";
      const type = "{{ message.tags }}";
      if (type != "success") statusClass = "#FF6467";

      Toastify({
        text: "{{message}}",
        duration: 3000,
        className: "btn",
        position: "right",
        style: {
          color: "black",
          background: statusClass,
        },
      }).showToast();
    </script>
    {% endfor %} {% endif %}
  </body>
</html>

main/templates/main/login.html
{% extends "main/layout.html" %} {% load static %} {% block content %}

<div class="w-full flex items-center justify-center">
  <div class="w-full max-w-md mx-3 p-8 mt-12 border-4 border-black h-fit">
    <h1 class="text-3xl text-black font-bold text-center mb-7">Bienvenido</h1>
    <form
      id="auth_form"
      class="space-y-6"
      method="POST"
      action="/login"
      method="post"
    >
      {% csrf_token %}
      <div>
        <label
          for="username"
          class="block text-sm font-semibold text-black mb-2"
        >
          Nombre de usuario
        </label>
        <input
          type="text"
          id="username"
          name="username"
          autofocus
          placeholder="Ingresa tu nombre de usuario"
          class="w-full px-4 py-3 border-[3px] border-black focus:outline-none bg-[#F5E6CF] focus:border-amber-500 font-semibold transition-colors duration-300"
        />
        <span id="error_username" class="text-red-500 font-semibold"></span>
      </div>

      <div>
        <label
          for="password"
          class="block text-sm font-semibold text-black mb-2"
        >
          Contraseña
        </label>
        <input
          type="password"
          name="password"
          id="password"
          placeholder="Ingresa tu contraseña"
          class="w-full px-4 py-3 border-[3px] border-black focus:outline-none bg-[#F5E6CF] focus:border-amber-500 font-semibold transition-colors duration-300"
        />
        <span id="error_password" class="text-red-500 font-semibold"></span>
      </div>

      <button type="submit" class="btn w-full bg-emerald-500">
        Iniciar Sesión
      </button>
    </form>
    <div class="mt-6 text-center">
      <a href="{% url 'inicio' %}" class="btn bg-slate-200">
        <i class="bi bi-chevron-left" style="font-weight: 800"></i> Volver a
        inicio
      </a>
    </div>
  </div>
</div>

<script src="{% static 'main/js/login.js' %}"></script>
{% endblock %}

main/templates/main/register.html
{% extends "main/layout.html" %} {% load static %} {% block content %}
<div class="w-full flex items-center justify-center">
  <div class="w-full max-w-md mx-3 p-8 mt-12 border-4 border-black h-fit">
    <h1 class="text-3xl font-bold text-center text-black mb-7">Registro</h1>
    <form
      id="auth_form"
      class="space-y-6"
      method="POST"
      action="/register"
      method="post"
    >
      {% csrf_token %}
      <div>
        <label
          for="username"
          class="block text-sm font-semibold text-black mb-2"
        >
          Nombre de usuario
        </label>
        <input
          type="text"
          id="username"
          name="username"
          autofocus
          placeholder="Ingresa tu nombre de usuario"
          class="w-full px-4 py-3 border-[3px] border-black focus:outline-none bg-[#F5E6CF] focus:border-amber-500 font-semibold transition-colors duration-300"
        />
        <span id="error_username" class="text-red-500 font-semibold"></span>
      </div>

      <div>
        <label
          for="password1"
          class="block text-sm font-semibold text-black mb-2"
        >
          Contraseña
        </label>
        <input
          type="password"
          name="password1"
          id="password1"
          placeholder="Ingresa tu contraseña"
          class="w-full px-4 py-3 border-[3px] border-black focus:outline-none bg-[#F5E6CF] focus:border-amber-500 font-semibold transition-colors duration-300"
        />
        <span id="error_password1" class="text-red-500 font-semibold"></span>
      </div>
      <div>
        <label
          for="password2"
          class="block text-sm font-semibold text-black mb-2"
        >
          Repite la contraseña
        </label>
        <input
          type="password"
          name="password2"
          id="password2"
          placeholder="Contraseña de validacion"
          class="w-full px-4 py-3 border-[3px] border-black focus:outline-none bg-[#F5E6CF] focus:border-amber-500 font-semibold transition-colors duration-300"
        />
        <span id="error_password2" class="text-red-500 font-semibold"></span>
      </div>

      <button type="submit" class="btn w-full bg-emerald-500">
        Registrarse
      </button>
    </form>
    <div class="mt-6 text-center">
      <a href="{% url 'inicio' %}" class="btn bg-slate-200">
        <i class="bi bi-chevron-left" style="font-weight: 800"></i> Volver a
        inicio
      </a>
    </div>
  </div>
</div>
<script src="{% static 'main/js/register.js' %}"></script>

{% endblock %}